version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres-book
    restart: always
    environment:
      POSTGRES_DB: book_journal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: spring-book
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/book_journal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_SHOW_SQL: true
      PORT: 8080

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-book
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  prometheus:
    image: prom/prometheus
    container_name: prometheus-book

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - backend

  grafana:
    image: grafana/grafana

    container_name: grafana-book

    ports:
      - "3000:3000"

    depends_on:
      - prometheus
  
  nginx-waf:
    image: nginx:alpine
    container_name: nginx-waf-book
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

volumes:
  postgres_data:

