events {}

http {
    server_tokens off;
    client_max_body_size 10M;
    limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;

    server {
        listen 80;

        if ($request_method !~ ^(GET|POST|PUT|DELETE|OPTIONS)$) {
            return 405;
        }

        if ($query_string ~* "(union|select|insert|drop|delete|script)") {
            return 403;
        }

        location / {
            limit_req zone=api burst=20 nodelay;
            proxy_pass http://spring-book:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
