# ==============================
# CONFIGURACIONES PARA EJECUTARLO DE FORMA LOCAL
# ==============================
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/book_journal}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
# spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
# spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

# server.port=${PORT:8080}
# spring.datasource.hikari.initializationFailTimeout=0
# spring.datasource.hikari.connectionTimeout=30000

# logging.level.root=INFO
# logging.level.org.springframework=DEBUG

# ===============================
# CONFIGURACIONES PARA EL SERVICIO (CLOUD RUN)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql:///bookjournal}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bookjournal2}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:db-password}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

server.port=${PORT:8080}

spring.datasource.hikari.initializationFailTimeout=0
spring.datasource.hikari.connectionTimeout=30000

logging.level.root=INFO
logging.level.org.springframework=INFO