spring.application.name=bookjournal-api
spring.web.resources.static-locations=classpath:/static/
server.port=9090
 
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/bookjournal_db
spring.datasource.username=postgres
spring.datasource.password=091223
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update